# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TP Planning' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TP Planning
  pod 'SideMenuSwift'
  pod 'IQDropDownTextField'

end
